// Build a YouTube-ready .srt from the word-level captions of a footage source.
// The word timings live in src/shorts/captions*.ts (generated by transcribe.mjs);
// this groups them into readable cues. Long-form Finals ship with an SRT so the
// upload has real captions (see AGENTS.md).
//
//   node scripts/make-srt.mjs [source.mp4] [out.srt] [totalFrames]
//
// Defaults: talking-head.mp4 -> out/<source>-captions.srt
// Pass the Final's total frame count (e.g. HABITS_DUR) to clamp the last cue to
// the exact video length — whisper glues trailing silence onto the final word.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const FPS = 30;
const MAX_WORDS = 9;   // hard cap per cue
const MAX_FRAMES = 108; // ~3.6s per cue
const GAP_FRAMES = 15;  // a >0.5s pause forces a break
const MAX_HOLD = 210;   // clamp a cue's on-screen time (~7s) — whisper glues trailing silence onto the last word
const WRAP = 42;        // chars per line before wrapping to a 2nd line

const source = process.argv[2] ?? "talking-head.mp4";
const outArg = process.argv[3];
const totalFrames = process.argv[4] ? Number(process.argv[4]) : null;

// map footage file -> its captions .ts (talking-head.mp4 = the live captionsData)
function captionsFile(src) {
  if (src === "talking-head.mp4") return "src/shorts/captionsData.ts";
  if (src === "claude-code-tutorial-final.mp4") return "src/tutorial-captions.ts";
  const m = src.match(/^talking-head-(\d{6})\.mp4$/);
  if (m) return `src/shorts/captions-${m[1]}.ts`;
  throw new Error(`no captions file mapping for "${src}"`);
}

function loadWords(file) {
  const raw = readFileSync(file, "utf8");
  const start = raw.indexOf('[{"text"');
  const end = raw.indexOf("}];", start);
  if (start === -1 || end === -1) throw new Error(`could not find caption array in ${file}`);
  // drop whisper artifacts like [BLANK_AUDIO] / [MUSIC] (they also bloat cue timing)
  return JSON.parse(raw.slice(start, end + 2))
    .map((w) => ({ ...w, text: w.text.replace(/\[[^\]]*\]/g, "").trim() }))
    .filter((w) => w.text.length > 0);
}

function ts(frame) {
  const totalMs = Math.round((frame / FPS) * 1000);
  const ms = totalMs % 1000;
  const s = Math.floor(totalMs / 1000) % 60;
  const m = Math.floor(totalMs / 60000) % 60;
  const h = Math.floor(totalMs / 3600000);
  const p = (n, w = 2) => String(n).padStart(w, "0");
  return `${p(h)}:${p(m)}:${p(s)},${p(ms, 3)}`;
}

function wrap(text) {
  if (text.length <= WRAP) return text;
  const words = text.split(" ");
  const a = [];
  let i = 0;
  for (; i < words.length; i++) {
    if (a.length > 0 && [...a, words[i]].join(" ").length > WRAP) break;
    a.push(words[i]);
  }
  const b = words.slice(i);
  return b.length ? `${a.join(" ")}\n${b.join(" ")}` : a.join(" ");
}

function endsSentence(t) {
  return /[.!?]["')\]]?$/.test(t);
}

function buildCues(words) {
  const cues = [];
  let cur = [];
  for (let i = 0; i < words.length; i++) {
    cur.push(words[i]);
    const next = words[i + 1];
    const durFrames = cur[cur.length - 1].to - cur[0].from;
    const gapNext = next ? next.from - words[i].to : Infinity;
    const flush =
      !next ||
      (endsSentence(words[i].text) && cur.length >= 3) ||
      cur.length >= MAX_WORDS ||
      durFrames >= MAX_FRAMES ||
      gapNext > GAP_FRAMES;
    if (flush) {
      const from = cur[0].from;
      let to = Math.min(cur[cur.length - 1].to, from + MAX_HOLD);
      if (totalFrames) to = Math.min(to, totalFrames);
      cues.push({ from, to, text: cur.map((w) => w.text).join(" ") });
      cur = [];
    }
  }
  return cues;
}

const file = captionsFile(source);
const words = loadWords(file);
const cues = buildCues(words);

const srt = cues
  .map((c, i) => `${i + 1}\n${ts(c.from)} --> ${ts(c.to)}\n${wrap(c.text)}\n`)
  .join("\n");

const out = outArg ?? `out/${source.replace(/\.mp4$/, "")}-captions.srt`;
mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(out, srt);
console.log(`wrote ${out} — ${cues.length} cues from ${words.length} words (${file})`);
