// Generates word-level captions from the talking-head VO with whisper.cpp and
// writes them (in absolute source frames @ 30fps) to src/shorts/captionsData.ts.
//
//   node scripts/transcribe.mjs [sourceFile] [model]
//
// Defaults: public/talking-head.mp4, model "base.en". Re-run after new footage.
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { installWhisperCpp, downloadWhisperModel, transcribe, toCaptions } from "@remotion/install-whisper-cpp";

const FPS = 30;
const ROOT = process.cwd();
const SRC = process.argv[2] ?? "public/talking-head.mp4";
const MODEL = process.argv[3] ?? "base.en";
const FF = "C:/ProgramData/chocolatey/bin/ffmpeg.exe";
const WHISPER_DIR = path.join(ROOT, "whisper.cpp");
const TMP = path.join(ROOT, "out", "_vo-16k.wav");

const main = async () => {
  mkdirSync(path.join(ROOT, "out"), { recursive: true });

  console.log("1/4 extracting 16kHz mono wav…");
  // loudnorm: the VO is recorded quiet (~-34 dB mean); normalizing helps whisper.
  execFileSync(FF, ["-y", "-hide_banner", "-loglevel", "error", "-i", SRC, "-af", "loudnorm=I=-16:TP=-1.5", "-ar", "16000", "-ac", "1", TMP]);

  console.log("2/4 installing whisper.cpp + model (first run downloads)…");
  await installWhisperCpp({ to: WHISPER_DIR, version: "1.5.5" });
  await downloadWhisperModel({ model: MODEL, folder: WHISPER_DIR });

  console.log("3/4 transcribing (this takes a few minutes)…");
  const whisperCppOutput = await transcribe({
    inputPath: TMP,
    whisperPath: WHISPER_DIR,
    whisperCppVersion: "1.5.5",
    model: MODEL,
    tokenLevelTimestamps: true,
  });

  const { captions } = toCaptions({ whisperCppOutput });
  const words = [];
  for (const c of captions) {
    const raw = c.text;
    const text = raw.trim().replace(/"/g, "'");
    if (text.length === 0) continue;
    const isPunct = /^[^\p{L}\p{N}]+$/u.test(text);
    // Tokens WITHOUT a leading space are subword continuations ("Anthrop"+"ic");
    // punctuation-only tokens ("," "." "?") are orphans. Both glue onto the
    // previous word so captions never show broken fragments.
    if ((isPunct || !raw.startsWith(" ")) && words.length > 0) {
      words[words.length - 1].text += text;
      words[words.length - 1].to = Math.round((c.endMs / 1000) * FPS);
      continue;
    }
    words.push({
      text,
      from: Math.round((c.startMs / 1000) * FPS),
      to: Math.round((c.endMs / 1000) * FPS),
    });
  }

  // Whisper mishears brand names — repair known multi-word splits, then fix
  // casing/spelling on single words. Extend these maps as new names appear.
  const JOINS = [
    [["anthrop", "ic"], "Anthropic"],
    [["f", "able"], "Fable"],
    [["m", "iff", "os"], "Mythos"],
    [["miff", "os"], "Mythos"],
  ];
  const norm = (s) => s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
  for (const [parts, joined] of JOINS) {
    for (let i = 0; i <= words.length - parts.length; i++) {
      if (parts.every((p, k) => norm(words[i + k].text) === p)) {
        const tail = words[i + parts.length - 1];
        const trailing = tail.text.match(/[^\p{L}\p{N}]+$/u)?.[0] ?? "";
        words.splice(i, parts.length, { text: joined + trailing, from: words[i].from, to: tail.to });
      }
    }
  }
  const FIX = { anthropic: "Anthropic", thorpek: "Anthropic", fable: "Fable", mythos: "Mythos", miffos: "Mythos", claude: "Claude" };
  for (const w of words) {
    const base = norm(w.text);
    if (FIX[base]) w.text = w.text.replace(/[\p{L}\p{N}]+/u, FIX[base]);
  }

  // Words that are OFTEN brand mishears but can also be legit (e.g. whisper
  // hears "Claude" as "cloud") — never auto-replace; print them with
  // timestamps so every flagged word gets a manual look before shipping.
  const REVIEW = ["cloud", "clod", "claud", "opis", "sonet", "fabel"];
  const flagged = words.filter((w) => REVIEW.includes(norm(w.text)));
  if (flagged.length) {
    console.warn(`REVIEW: ${flagged.length} possible brand mishear(s) — check each in context:`);
    for (const w of flagged) console.warn(`  "${w.text}" @ ${(w.from / FPS).toFixed(1)}s (frame ${w.from})`);
  }

  console.log(`4/4 writing ${words.length} words -> src/shorts/captionsData.ts`);
  const body =
    `// AUTO-GENERATED by scripts/transcribe.mjs — do not edit by hand.\n` +
    `// Word-level captions in absolute source frames (frame = seconds × 30).\n` +
    `export type CaptionWord = { text: string; from: number; to: number };\n\n` +
    `export const CAPTIONS: CaptionWord[] = ${JSON.stringify(words)};\n`;
  writeFileSync(path.join(ROOT, "src", "shorts", "captionsData.ts"), body);
  console.log("done.");
};

main().catch((e) => {
  console.error("transcribe failed:", e?.message ?? e);
  process.exit(1);
});
