// Precompute per-frame voice loudness from the talking-head VO so scenes can
// react to the voice WITHOUT decoding audio at render time (render-safe).
// Usage: node scripts/voice-levels.mjs [source] [fps]
// Writes src/motion/voiceLevels.ts (bundled data, read by useVoiceLevel()).
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const src = process.argv[2] ?? "public/talking-head.mp4";
const fps = Number(process.argv[3] ?? 30);
const SR = 16000;

console.log(`Decoding ${src} → mono ${SR}Hz WAV…`);
const tmp = join(tmpdir(), `vo-levels-${Date.now()}.wav`);
mkdirSync(tmpdir(), { recursive: true });
const ff = spawnSync("npx", ["remotion", "ffmpeg", "-y", "-i", src, "-ac", "1", "-ar", String(SR), "-c:a", "pcm_s16le", "-v", "error", JSON.stringify(tmp)], {
  shell: true,
});
if (ff.status !== 0) {
  console.error(ff.stderr?.toString() ?? "ffmpeg failed");
  process.exit(1);
}

// strip the WAV container: PCM starts after the "data" chunk header
const wav = readFileSync(tmp);
rmSync(tmp, { force: true });
const dataIdx = wav.indexOf(Buffer.from("data"));
if (dataIdx < 0) {
  console.error("No data chunk in WAV output");
  process.exit(1);
}
const pcm = wav.subarray(dataIdx + 8);
const samplesPerFrame = Math.round(SR / fps);
const frames = Math.floor(pcm.length / 2 / samplesPerFrame);
const rms = new Array(frames);
let peak = 0;
for (let f = 0; f < frames; f++) {
  let sum = 0;
  const base = f * samplesPerFrame * 2;
  for (let s = 0; s < samplesPerFrame; s++) {
    const v = pcm.readInt16LE(base + s * 2) / 32768;
    sum += v * v;
  }
  rms[f] = Math.sqrt(sum / samplesPerFrame);
  if (rms[f] > peak) peak = rms[f];
}
// normalize 0..1 against the loudest frame, round to 2dp for a compact file
const levels = rms.map((v) => Math.round((v / (peak || 1)) * 100) / 100);

const out = `// AUTO-GENERATED by scripts/voice-levels.mjs — do not edit by hand.
// Per-frame VO loudness (0..1, ${fps}fps) for ${JSON.stringify(src)}.
export const VOICE_LEVELS: number[] = ${JSON.stringify(levels)};
`;
writeFileSync("src/motion/voiceLevels.ts", out);
console.log(`Wrote src/motion/voiceLevels.ts (${frames} frames, peak-normalized).`);
